import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App on Zeabur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> on <a href="https://zeabur.com">Zeabur</a>!
        </h1>
      </main>

      <footer className={styles.footer}>
        <a href="https://zeabur.com">
          <img
            src="https://zeabur.com/logo-with-text-white.svg"
            style={{ height: 32 }}
          />
        </a>
      </footer>
    </div>
  )
}

export default Home
